//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projem_Otel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteriler
    {
        public int MusteriID { get; set; }
        public string TC { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public int SehirID { get; set; }
        public System.DateTime GelisTarihi { get; set; }
        public System.DateTime CikisTarihi { get; set; }
        public System.DateTime DogumTarihi { get; set; }
        public string Telefon { get; set; }
        public int OdaTuruID { get; set; }
        public int DurumID { get; set; }
    
        public virtual Durum Durum { get; set; }
        public virtual OdaTurleri OdaTurleri { get; set; }
        public virtual Sehirler Sehirler { get; set; }
    }
}
