//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projem_Otel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odalar
    {
        public int OdaID { get; set; }
        public string OdaTuru { get; set; }
        public string Dolu { get; set; }
        public string OdaDurumu { get; set; }
        public Nullable<int> OdaTuruID { get; set; }
    
        public virtual OdaTurleri OdaTurleri { get; set; }
    }
}
