//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projem_Otel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public string TC { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string SehirAd { get; set; }
        public System.DateTime GelisTarihi { get; set; }
        public System.DateTime CikisTarihi { get; set; }
        public System.DateTime DogumTarihi { get; set; }
        public string Telefon { get; set; }
        public string OdaTuru { get; set; }
        public string Durum { get; set; }
    }
}
